### ISSUE TITLE
Binary data type returned as a Buffer object

### ISSUE THREAD

**Issue by tim-phillips** [AbdullahZN/node-dynamo#11]
I have a binary data type in a field named 'active' in dynamodb, but when returning it I get the following instead of a javascript `true`. 

```
active: {
  type: "Buffer",
  data: [182, 187, 158]
}
```

Is this intentional or should we be returning a javascript boolean?

**Comment by AbdullahZN** [comment]
Well if you expect a boolean, shouldn't you put it as a boolean ?

As DynamoDB stores the actual data as an array of unsigned byte, this is probably why you getting this as a result.

**Comment by tim-phillips** [comment]
I did put it as a boolean in the dynamodb console, the above is what I get back. 

I'd be willing to work on a PR to convert the unsigned byte to a JavaScript Boolean if that would align with the intent of this library.

**Comment by AbdullahZN** [comment]
I meant store it as a boolean type inside table, in this case you'll get `{ active: true }`.

However, I don't think its a good idea to alter AWS SDK's original result.
You just have to do a `toString()` to get the actual data in this case.
