### ISSUE TITLE
Unable to set credentials

### ISSUE THREAD

**Issue by tim-phillips** [AbdullahZN/node-dynamo#16]
The hosting service I'm using reserves `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`: https://zeit.co/docs/v2/deployments/environment-variables-and-secrets#reserved-variables

Also, it's not ok to upload files with security credentials to the hosting environment. 

Is there a way to set creds in this library besides those two documented ways?

**Comment by tim-phillips** [comment]
I made this just to make my code work. There's not a great way to add the extra config since there's no options object. Would have to be a breaking change, and not actually implemented this way.

https://github.com/tim-phillips/dynamo-node/commit/0c7d275d41a3ea5dff8f87b7510d2298f76841fd

**Comment by AbdullahZN** [comment]
Hi @tim-phillips, thanks for pointing this.
I committed https://github.com/AbdullahZN/dynamo-node/commit/eb422ad52677176cf9ad0a1e4a99f5822dadcd16#diff-168726dbe96b3ce427e7fedce31bb0bcR9 
Which should fix the issue without breaking anything :)

**Comment by tim-phillips** [comment]
Wonderful! Can you publish?

**Comment by AbdullahZN** [comment]
Done 🙂 
Closing this then 👍Thank you for pointing this out!
